### ISSUE TITLE
Публиковать многодневные события правильно

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/calendar-bot#7]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/105274/61865918-d6207400-aedc-11e9-9a0e-e21e0aa00044.png">

```yml
name: FrontendConf
date: 13.10.2019-14.10.2019
city: Москва
link: https://frontendconf.ru/moscow/2019
```

То есть нужно было написать `13–14 октября 2019`, если тот же месяц или `31 октября—1 ноября 2019`, если на стыке.
